apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-register-staging
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-register-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/php-simple-register/staging
    repoURL: https://github.com/Olad03/app-register-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
